window.CAPACITY_ANALYSIS = {
  "generatedAt": "2026-06-27",
  "sourceFile": "30.5.2026 Capacity utilization rate 产能利用率.xlsx",
  "workbookFile": "reports/Machine_Capacity_Analysis_2026-06-27.xlsx",
  "basis": {
    "hoursPerDay": 10,
    "workingDaysPerMonth": 26
  },
  "overview": {
    "recordCount": 247,
    "machineCount": 30,
    "totalDemand": 26831601,
    "totalMonthlyCapacity": 63365975,
    "totalRequiredShifts": 1266.4,
    "totalAvailableShifts": 884,
    "totalUtilization": 1.4326,
    "overCapacity": 17,
    "highLoad": 3,
    "normal": 6,
    "lowLoad": 4,
    "machineGap": 29,
    "topMachine": {
      "rank": 1,
      "sheet": "CNC一共 6台",
      "machine": "3-Axis CNC",
      "productCount": 10,
      "monthlyDemand": 124070,
      "dailyCapacity10h": 2700,
      "monthlyCapacity26d": 70200,
      "requiredShifts": 208.3,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 8.0131,
      "additionalShifts": 182.3,
      "machinesRequired": 9,
      "machineGap": 8,
      "weightedOee": 0.75,
      "status": "Over capacity",
      "statusClass": "danger"
    }
  },
  "machines": [
    {
      "rank": 1,
      "sheet": "CNC一共 6台",
      "machine": "3-Axis CNC",
      "productCount": 10,
      "monthlyDemand": 124070,
      "dailyCapacity10h": 2700,
      "monthlyCapacity26d": 70200,
      "requiredShifts": 208.3,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 8.0131,
      "additionalShifts": 182.3,
      "machinesRequired": 9,
      "machineGap": 8,
      "weightedOee": 0.75,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 2,
      "sheet": "折弯 BENDING",
      "machine": "折弯",
      "productCount": 12,
      "monthlyDemand": 28000,
      "dailyCapacity10h": 900,
      "monthlyCapacity26d": 23400,
      "requiredShifts": 75,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 2.8846,
      "additionalShifts": 49,
      "machinesRequired": 3,
      "machineGap": 2,
      "weightedOee": 0.75,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 3,
      "sheet": "TAP产能分析",
      "machine": "TAP产能分析",
      "productCount": 5,
      "monthlyDemand": 623332,
      "dailyCapacity10h": 10000,
      "monthlyCapacity26d": 260000,
      "requiredShifts": 72.4,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 2.7836,
      "additionalShifts": 46.4,
      "machinesRequired": 3,
      "machineGap": 2,
      "weightedOee": null,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 4,
      "sheet": "200T单冲11#",
      "machine": "200 T",
      "productCount": 22,
      "monthlyDemand": 92301,
      "dailyCapacity10h": 6720,
      "monthlyCapacity26d": 174720,
      "requiredShifts": 70.7,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 2.7203,
      "additionalShifts": 44.7,
      "machinesRequired": 3,
      "machineGap": 2,
      "weightedOee": 0.665,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 5,
      "sheet": "260T 单冲 10#",
      "machine": "设备 260T",
      "productCount": 25,
      "monthlyDemand": 75227,
      "dailyCapacity10h": 2040,
      "monthlyCapacity26d": 53040,
      "requiredShifts": 62.1,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 2.3902,
      "additionalShifts": 36.1,
      "machinesRequired": 3,
      "machineGap": 2,
      "weightedOee": 0.85,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 6,
      "sheet": "CNC一共 6台",
      "machine": "4-Axis CNC",
      "productCount": 2,
      "monthlyDemand": 6500,
      "dailyCapacity10h": 150,
      "monthlyCapacity26d": 3900,
      "requiredShifts": 61.7,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 2.3718,
      "additionalShifts": 35.7,
      "machinesRequired": 3,
      "machineGap": 2,
      "weightedOee": 0.75,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 7,
      "sheet": "压铸机 350T",
      "machine": "CNC 压铸机",
      "productCount": 3,
      "monthlyDemand": 84481,
      "dailyCapacity10h": 3600,
      "monthlyCapacity26d": 93600,
      "requiredShifts": 45.6,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.7527,
      "additionalShifts": 19.6,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.7775,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 8,
      "sheet": "150T产能6#",
      "machine": "150T产能6#",
      "productCount": 2,
      "monthlyDemand": 221666,
      "dailyCapacity10h": 5000,
      "monthlyCapacity26d": 130000,
      "requiredShifts": 44.3,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.7051,
      "additionalShifts": 18.3,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": null,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 9,
      "sheet": "Robot welding",
      "machine": "M/C :RW1",
      "productCount": 4,
      "monthlyDemand": 27800,
      "dailyCapacity10h": 4896,
      "monthlyCapacity26d": 127296,
      "requiredShifts": 40.8,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.5696,
      "additionalShifts": 14.8,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.85,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 10,
      "sheet": "110T 产能单冲9#",
      "machine": "110T",
      "productCount": 10,
      "monthlyDemand": 75400,
      "dailyCapacity10h": 2100,
      "monthlyCapacity26d": 54600,
      "requiredShifts": 38.8,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.4908,
      "additionalShifts": 12.8,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.7,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 11,
      "sheet": "300T 产能分析 7#",
      "machine": "300T",
      "productCount": 25,
      "monthlyDemand": 459332,
      "dailyCapacity10h": 21000,
      "monthlyCapacity26d": 546000,
      "requiredShifts": 38.7,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.487,
      "additionalShifts": 12.7,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.7,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 12,
      "sheet": "Robot welding",
      "machine": "M/C :RW2",
      "productCount": 6,
      "monthlyDemand": 13500,
      "dailyCapacity10h": 775.2,
      "monthlyCapacity26d": 20155,
      "requiredShifts": 36.3,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.3981,
      "additionalShifts": 10.3,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.85,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 13,
      "sheet": "110T产能5#",
      "machine": "110T 按10H",
      "productCount": 21,
      "monthlyDemand": 5851821,
      "dailyCapacity10h": 129600,
      "monthlyCapacity26d": 6739200,
      "requiredShifts": 72.1,
      "currentEquipment": 2,
      "availableShifts": 52,
      "utilization": 1.3872,
      "additionalShifts": 20.1,
      "machinesRequired": 3,
      "machineGap": 1,
      "weightedOee": 0.7025,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 14,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW3",
      "productCount": 4,
      "monthlyDemand": 30000,
      "dailyCapacity10h": 1122,
      "monthlyCapacity26d": 29172,
      "requiredShifts": 35,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.3471,
      "additionalShifts": 9,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.85,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 15,
      "sheet": "Rivet",
      "machine": "M/C :RV2",
      "productCount": 6,
      "monthlyDemand": 55000,
      "dailyCapacity10h": 2550,
      "monthlyCapacity26d": 66300,
      "requiredShifts": 31.4,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.2066,
      "additionalShifts": 5.4,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.85,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 16,
      "sheet": "110T产能3#",
      "machine": "110T 按10H",
      "productCount": 16,
      "monthlyDemand": 4908505,
      "dailyCapacity10h": 129600,
      "monthlyCapacity26d": 6739200,
      "requiredShifts": 55.8,
      "currentEquipment": 2,
      "availableShifts": 52,
      "utilization": 1.0728,
      "additionalShifts": 3.8,
      "machinesRequired": 3,
      "machineGap": 1,
      "weightedOee": 0.7279,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 17,
      "sheet": "Rivet",
      "machine": "M/C :RV1",
      "productCount": 6,
      "monthlyDemand": 40000,
      "dailyCapacity10h": 2040,
      "monthlyCapacity26d": 53040,
      "requiredShifts": 27,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 1.037,
      "additionalShifts": 1,
      "machinesRequired": 2,
      "machineGap": 1,
      "weightedOee": 0.85,
      "status": "Over capacity",
      "statusClass": "danger"
    },
    {
      "rank": 18,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW4",
      "productCount": 7,
      "monthlyDemand": 15700,
      "dailyCapacity10h": 765,
      "monthlyCapacity26d": 19890,
      "requiredShifts": 25.3,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.9737,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "High load",
      "statusClass": "warning"
    },
    {
      "rank": 19,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW2",
      "productCount": 1,
      "monthlyDemand": 120000,
      "dailyCapacity10h": 5100,
      "monthlyCapacity26d": 132600,
      "requiredShifts": 23.5,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.905,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "High load",
      "statusClass": "warning"
    },
    {
      "rank": 20,
      "sheet": "500T 产能分析8#",
      "machine": "500T",
      "productCount": 17,
      "monthlyDemand": 242500,
      "dailyCapacity10h": 21000,
      "monthlyCapacity26d": 546000,
      "requiredShifts": 22.8,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.8773,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.7,
      "status": "High load",
      "statusClass": "warning"
    },
    {
      "rank": 21,
      "sheet": "80T产能1#",
      "machine": "80T No.1#",
      "productCount": 13,
      "monthlyDemand": 2907150,
      "dailyCapacity10h": 201600,
      "monthlyCapacity26d": 10483200,
      "requiredShifts": 39.4,
      "currentEquipment": 2,
      "availableShifts": 52,
      "utilization": 0.7579,
      "additionalShifts": 0,
      "machinesRequired": 2,
      "machineGap": 0,
      "weightedOee": 0.6,
      "status": "Normal",
      "statusClass": "ok"
    },
    {
      "rank": 22,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW6",
      "productCount": 4,
      "monthlyDemand": 10000,
      "dailyCapacity10h": 510,
      "monthlyCapacity26d": 13260,
      "requiredShifts": 19.6,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.7541,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "Normal",
      "statusClass": "ok"
    },
    {
      "rank": 23,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW7",
      "productCount": 4,
      "monthlyDemand": 10000,
      "dailyCapacity10h": 510,
      "monthlyCapacity26d": 13260,
      "requiredShifts": 19.6,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.7541,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "Normal",
      "statusClass": "ok"
    },
    {
      "rank": 24,
      "sheet": "80T高速冲产能2#",
      "machine": "80T NO.",
      "productCount": 5,
      "monthlyDemand": 9410032,
      "dailyCapacity10h": 1197000,
      "monthlyCapacity26d": 31122000,
      "requiredShifts": 18.5,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.7097,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.6799,
      "status": "Normal",
      "statusClass": "ok"
    },
    {
      "rank": 25,
      "sheet": "压铸机 650T",
      "machine": "压铸机",
      "productCount": 2,
      "monthlyDemand": 5700,
      "dailyCapacity10h": 360,
      "monthlyCapacity26d": 9360,
      "requiredShifts": 15.8,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.609,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.6,
      "status": "Normal",
      "statusClass": "ok"
    },
    {
      "rank": 26,
      "sheet": "110T产能4#",
      "machine": "110T 按10H",
      "productCount": 5,
      "monthlyDemand": 1066584,
      "dailyCapacity10h": 90000,
      "monthlyCapacity26d": 4680000,
      "requiredShifts": 26.6,
      "currentEquipment": 2,
      "availableShifts": 52,
      "utilization": 0.5121,
      "additionalShifts": 0,
      "machinesRequired": 2,
      "machineGap": 0,
      "weightedOee": 0.6098,
      "status": "Normal",
      "statusClass": "ok"
    },
    {
      "rank": 27,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW5",
      "productCount": 4,
      "monthlyDemand": 5500,
      "dailyCapacity10h": 459,
      "monthlyCapacity26d": 11934,
      "requiredShifts": 12,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.4609,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "Low load",
      "statusClass": "idle"
    },
    {
      "rank": 28,
      "sheet": "150T产能6#",
      "machine": "150T",
      "productCount": 3,
      "monthlyDemand": 313000,
      "dailyCapacity10h": 43200,
      "monthlyCapacity26d": 1123200,
      "requiredShifts": 10,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.3846,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.6,
      "status": "Low load",
      "statusClass": "idle"
    },
    {
      "rank": 29,
      "sheet": "Robot welding",
      "machine": "M/C :RW3",
      "productCount": 1,
      "monthlyDemand": 2500,
      "dailyCapacity10h": 255,
      "monthlyCapacity26d": 6630,
      "requiredShifts": 9.8,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.3771,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "Low load",
      "statusClass": "idle"
    },
    {
      "rank": 30,
      "sheet": "MC Spot welding",
      "machine": "M/C:SW1",
      "productCount": 2,
      "monthlyDemand": 6000,
      "dailyCapacity10h": 800.7,
      "monthlyCapacity26d": 20818,
      "requiredShifts": 7.5,
      "currentEquipment": 1,
      "availableShifts": 26,
      "utilization": 0.2882,
      "additionalShifts": 0,
      "machinesRequired": 1,
      "machineGap": 0,
      "weightedOee": 0.85,
      "status": "Low load",
      "statusClass": "idle"
    }
  ],
  "statusCounts": [
    {
      "label": "Over capacity",
      "count": 17,
      "className": "danger"
    },
    {
      "label": "High load",
      "count": 3,
      "className": "warning"
    },
    {
      "label": "Normal",
      "count": 6,
      "className": "ok"
    },
    {
      "label": "Low load",
      "count": 4,
      "className": "idle"
    }
  ],
  "topProducts": [
    {
      "rank": 1,
      "machine": "3-Axis CNC",
      "productName": "LOWER SHEET METAL ASSEMBLY",
      "productSpec": "",
      "monthlyForecast": 10000,
      "dailyCapacity10h": 200,
      "requiredShifts": 50,
      "utilization": 1.9231
    },
    {
      "rank": 2,
      "machine": "4-Axis CNC",
      "productName": "RHS ACTIVE BRACKET",
      "productSpec": "",
      "monthlyForecast": 4500,
      "dailyCapacity10h": 93.1,
      "requiredShifts": 48.3,
      "utilization": 1.859
    },
    {
      "rank": 3,
      "machine": "3-Axis CNC",
      "productName": "3DU RESOLVER COVER",
      "productSpec": "",
      "monthlyForecast": 10000,
      "dailyCapacity10h": 257.1,
      "requiredShifts": 38.9,
      "utilization": 1.4957
    },
    {
      "rank": 4,
      "machine": "3-Axis CNC",
      "productName": "Bracket",
      "productSpec": "",
      "monthlyForecast": 25000,
      "dailyCapacity10h": 675,
      "requiredShifts": 37,
      "utilization": 1.4245
    },
    {
      "rank": 5,
      "machine": "折弯",
      "productName": "NLC BOX 600",
      "productSpec": "",
      "monthlyForecast": 5500,
      "dailyCapacity10h": 225,
      "requiredShifts": 24.4,
      "utilization": 0.9402
    },
    {
      "rank": 6,
      "machine": "M/C:SW2",
      "productName": "UPPER PLATE",
      "productSpec": "",
      "monthlyForecast": 120000,
      "dailyCapacity10h": 5100,
      "requiredShifts": 23.5,
      "utilization": 0.905
    },
    {
      "rank": 7,
      "machine": "150T产能6#",
      "productName": "机构左右侧板L",
      "productSpec": "48187088AA",
      "monthlyForecast": 110833,
      "dailyCapacity10h": 5000,
      "requiredShifts": 22.2,
      "utilization": 0.8526
    },
    {
      "rank": 8,
      "machine": "150T产能6#",
      "productName": "机构左右侧板R",
      "productSpec": "48187089AA",
      "monthlyForecast": 110833,
      "dailyCapacity10h": 5000,
      "requiredShifts": 22.2,
      "utilization": 0.8526
    },
    {
      "rank": 9,
      "machine": "3-Axis CNC",
      "productName": "PASSIVE BRACKET",
      "productSpec": "",
      "monthlyForecast": 4000,
      "dailyCapacity10h": 195.7,
      "requiredShifts": 20.4,
      "utilization": 0.7863
    },
    {
      "rank": 10,
      "machine": "M/C :RW1",
      "productName": "Gland plate",
      "productSpec": "",
      "monthlyForecast": 20000,
      "dailyCapacity10h": 1020,
      "requiredShifts": 19.6,
      "utilization": 0.7541
    },
    {
      "rank": 11,
      "machine": "3-Axis CNC",
      "productName": "",
      "productSpec": "",
      "monthlyForecast": 50370,
      "dailyCapacity10h": 2700,
      "requiredShifts": 18.7,
      "utilization": 0.7175
    },
    {
      "rank": 12,
      "machine": "M/C :RW1",
      "productName": "",
      "productSpec": "",
      "monthlyForecast": 3800,
      "dailyCapacity10h": 204,
      "requiredShifts": 18.6,
      "utilization": 0.7164
    },
    {
      "rank": 13,
      "machine": "CNC 压铸机",
      "productName": "",
      "productSpec": "",
      "monthlyForecast": 65481,
      "dailyCapacity10h": 3600,
      "requiredShifts": 18.2,
      "utilization": 0.6996
    },
    {
      "rank": 14,
      "machine": "CNC 压铸机",
      "productName": "",
      "productSpec": "",
      "monthlyForecast": 15000,
      "dailyCapacity10h": 840,
      "requiredShifts": 17.9,
      "utilization": 0.6868
    },
    {
      "rank": 15,
      "machine": "M/C :RW2",
      "productName": "",
      "productSpec": "",
      "monthlyForecast": 2000,
      "dailyCapacity10h": 112.2,
      "requiredShifts": 17.8,
      "utilization": 0.6856
    },
    {
      "rank": 16,
      "machine": "TAP产能分析",
      "productName": "LOAD TERM-HI",
      "productSpec": "48187055AA",
      "monthlyForecast": 138333,
      "dailyCapacity10h": 8000,
      "requiredShifts": 17.3,
      "utilization": 0.6651
    },
    {
      "rank": 17,
      "machine": "TAP产能分析",
      "productName": "LOAD TERM-LOW",
      "productSpec": "48187255AA",
      "monthlyForecast": 138333,
      "dailyCapacity10h": 8000,
      "requiredShifts": 17.3,
      "utilization": 0.6651
    },
    {
      "rank": 18,
      "machine": "M/C:SW3",
      "productName": "CG BASE",
      "productSpec": "",
      "monthlyForecast": 15000,
      "dailyCapacity10h": 872.1,
      "requiredShifts": 17.2,
      "utilization": 0.6615
    },
    {
      "rank": 19,
      "machine": "TAP产能分析",
      "productName": "MIDDLE TERMINAL",
      "productSpec": "48187096AA",
      "monthlyForecast": 125000,
      "dailyCapacity10h": 8000,
      "requiredShifts": 15.6,
      "utilization": 0.601
    },
    {
      "rank": 20,
      "machine": "110T 按10H",
      "productName": "金属支架",
      "productSpec": "51207070",
      "monthlyForecast": 3000000,
      "dailyCapacity10h": 96000,
      "requiredShifts": 31.3,
      "utilization": 0.601
    }
  ]
};
